### ISSUE TITLE
Semver constraints are wrongly marked as having no upper bound

### ISSUE THREAD

**Issue by stof** [psliwa/idea-composer-plugin#12]
``~1.4`` has an upper bound, but the plugin generates a warning for it telling it has no upper bound. This is wrong. Semver constraints (both ``~1.4`` and ``^1.4``) have an upper bound

**Comment by psliwa** [comment]
What PhpStorm and plugin version do you use? What quick fixes are suggested when you press alt+enter? When you add new dependency with for example `~1.4` version, the warning is also generated? Maybe this warning is cached from warning that was generated before version change (cache problem)?

A lot of questions, because I can not reproduce this issue ;)

**Comment by stof** [comment]
I cannot reproduce it anymore

**Comment by psliwa** [comment]
I think this was a cache problem. PhpStorm likes to cache a lot of things and rarely there are cache invalidation bugs.

**Comment by bingalls** [comment]
Whenever I make changes, I must *File->Invalidate Caches/Restart*.
Note `dev-master` is the only option for some packages, such as `bensquire/php-image-optim`, but I'd say current behavior is as expected.
I have packages in `require-dev` that I intend to keep as `dev-master`. It would be nice to have an option to suppress these warnings for `require-dev`

**Comment by psliwa** [comment]
You are able to suppress these warnings - there is "Exclude package xxx from unbounded version inspection" quick fix what does exactly what you expect.
