### ISSUE TITLE
Autocomplete does not work with JDK v6 on MacOSX (IntelliJ IDEA 14, 15 EAP)

### ISSUE THREAD

**Issue by bilekt3** [psliwa/idea-composer-plugin#15]
If JDK for IntelliJ IDEA is set to Mac default 6 then autocomplete of versions does not work. On v8 works as expected. 

After fresh install of 15 EAP and playing with JDK for run some notices about SSL was thrown to event log, but I am unable to reproduce it.

I use bundled v6 because of performance and graphical problems with both v8 on Mac OS X on retina displays (JetBrains - drain battery, Oracle looks weird).

**Comment by psliwa** [comment]
This is jre6 bug: http://stackoverflow.com/questions/6851461/java-why-does-ssl-handshake-give-could-not-generate-dh-keypair-exception

packagist enforces ssl connection, jre6 has a problems with certain ssl connections, so this is a source of the issue.

If you really want to use jre6 you should set BouncyCastle's JCE provider as default. There is a description how you can do this: http://docs.oracle.com/cd/E19830-01/819-4712/ablsc/index.html

I'm not sure the fix should be on plugin code level, BouncyCastle JCE is havy (almost 3mb - maybe proguard will help to make it smaller) - accepting all certificates for java6 is not an option for me, because this will be a security issue.

**Comment by psliwa** [comment]
I've closed the issue, because there is no good fix on the plugin level.
