### ISSUE TITLE
Why only for composer.json?

### ISSUE THREAD

**Issue by mindplay-dk** [psliwa/idea-composer-plugin#20]
If you can validate a JSON schema with this, why is the plugin limited to files named "composer.json"?

Why not enable it to work with any json-file and use the `$schema` key to enable support for composer.json or any other json-file with schema?

Just wondering :-)

**Comment by psliwa** [comment]
This plugin is not limited only to validate jsons, it also provide inspections and stuff that is specific for composer. But yes, good point :) On my todo list is support for other package managers, like bower.json, package.json etc. I don't know when it will come because composer is a priority :) Json schema reader in this plugin is very limited and does not support full json schema specification, has some additional composer specific features etc, so more changes are required.

**Comment by mindplay-dk** [comment]
I'm pretty sure you could find a full JSON schema validator as a third-party library?

Anyway, I'm sure pressure on JetBrains to officially support JSON schema will be increasing :-)

**Comment by psliwa** [comment]
Intellij 16 and PhpStorm 11 will have brought us support for json schema :)
