### ISSUE TITLE
Feature Request: Open project URL when CMD+Click on version constraint

### ISSUE THREAD

**Issue by lakhman** [psliwa/idea-composer-plugin#25]
Currently cmd+click on the project name opens the project in the vendor directory, could we also have it so command+click on the version constraint opens that particular version in github? - So we can quickly jump to the documentation. Basically an easier way of jumping to that project on github.

**Comment by psliwa** [comment]
There is already similar feature. When you have caret at package name, you can navigate to package homepage on packagist by shift + f1. This feature uses "quick documentation" pattern in IntelliJ. You are able also to go to given property documentation on getcomposer page in the same way.

Do you think this is enough or it should be improved somehow? Navigating directly to github is not so easy, because vendor/package on packagist name doesn't have to be the same as vendor/package on github and at most cases are different. Maybe fetching repository / documentation url from composer.lock would be ok, I will see :)

**Comment by lakhman** [comment]
ah nice, I didn't know of the shift + f1 feature, cmd + click on the version constraint to take you to packagist would be perfect, I understand linking to github may be an issue, what if the composer.lock file is not available? CMD + Click on the version currently does nothing, maybe we could use that to take you to packagist?

Thanks! Awesome plugin! Makes working with composer so much easier!

**Comment by psliwa** [comment]
In case when composer.lock is unavailable, the shortcut can lead to packagist as fallback. Making version clickable sounds ok and useful, so it will be done soon.

**Comment by psliwa** [comment]
I've implemented both features: navigation through clicking version constraint and getting documentation url from composer.lock if possible. This features will be available in new release.
