### ISSUE TITLE
Add support for scripts-dev

### ISSUE THREAD

**Issue by sergeyklay** [psliwa/idea-composer-plugin#26]
Composer plugin: https://github.com/neronmoon/scriptsdev

Result:

![selection_037](https://cloud.githubusercontent.com/assets/1256298/13012196/ebebe108-d1b2-11e5-8f48-604b5005180c.png)

**Comment by psliwa** [comment]
I am not convinced to support for schema provided by external plugins. According to official composer json schema, package definition does not allow extra properties. When you run `composer validate`, you get an error.

**Comment by sergeyklay** [comment]
So, wont fix?

**Comment by psliwa** [comment]
I think about new "quick fix" (alt+enter) called "Allow `x` property to be here" or something like that, so errors caused by custom properties would be able to ignore. What do you think about this solution?

**Comment by sergeyklay** [comment]
Of course I would like full support of composer's plugins on the API level. But in any case, it's better than nothing. Thanks

**Comment by psliwa** [comment]
It is hard to add support for schemas provided by custom plugins, because this is not standardised by composer api (probably even more - composer intentionally does not support this in clean way, because this approach is deprecated). If the plugins defined additional schema that they provide, it would be possible to fetch extra schema file and in runtime merge it with standard composer schema. Adding support for plugins one by one is not solution for me.

I can see also maybe better solution, define custom additional schema in project settings, something like "Type provider" in symfony 2 plugin (http://symfony2-plugin.espend.de/extension/signature_type.html#settings), so everyone would be able to add custom thing, ignore additional properties etc.
