### ISSUE TITLE
Support for tilde and caret operators in version autocompletion

### ISSUE THREAD

**Issue by jakzal** [psliwa/idea-composer-plugin#5]
It would be nice if plugin suggested caret or tilde operators when autocompleting versions. I think these suggestions should be at the top:

```
^1.0.1
~1.0.1
~1.0
1.*
1.0
1.0.*
...
```

I also think it'd be sufficient to only show them for the latest stable version.

**Comment by psliwa** [comment]
Tilde and caret operators are supported, but in different way. When you type "~" or "^" and trigger completion, only semantic versions and subversions would be suggested. I decided to do this in that way, because when you trigger completion and type "^" or "~", completion popup magically disappears. There are chars that cause completion popup disappearance (even when there are items that match typed prefix), e.g. "^", "~", "*", "/" and more non alphanum chars - I have not find a solution yet to prevent popup disapperance.

Versions sorting idea is great - It will be in next release.
