### ISSUE TITLE
Request: Support for PhpStorm2020.1

### ISSUE THREAD

**Issue by isakrubin** [psliwa/idea-composer-plugin#91]
`The PHP composer.json support (id=org.psliwa.idea.composer, path=~/.local/share/JetBrains/PhpStorm2020.1/ideaComposerPlugin, version=1.0.37) plugin was marked as incompatible.`

**Comment by RootProgger** [comment]
same @me

**Comment by psliwa** [comment]
Hi. Since 2020.1 all or the most features of this plugin should be
available in native php plugin - this is information from Jetbrains. If
there are missing features in native composer support let Jetbrains know in
their issue tracker. This plugin will be deprecated and I won’t add support
fo 2020.+ because there is no sense to do that.

W dniu pt., 7.02.2020 o 12:22 Marcus Wolf <notifications@github.com>
napisał(a):

**Comment by isakrubin** [comment]
That's great :)
Just fyi
It kept showing up as an error even though it was disabled.
Manually deleting the folder ~/.local/share/JetBrains/PhpStorm2020.1/ideaComposerPlugin solved it.
